# Generated by Django 2.1 on 2018-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='商品説明'),
        ),
    ]
