# Generated by Django 2.1 on 2018-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0003_auto_20180922_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(null=True, to='toy_app.Tag', verbose_name='タグ'),
        ),
    ]
