# Generated by Django 2.1 on 2018-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0005_auto_20180922_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='toy_app.Tag', verbose_name='タグ'),
        ),
    ]
