# Generated by Django 2.1 on 2018-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0007_auto_20180924_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='official_url',
            field=models.URLField(null=True, verbose_name='公式URL'),
        ),
    ]
