# Generated by Django 2.1 on 2018-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0008_item_official_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='item',
            name='official_url',
            field=models.URLField(blank=True, null=True, verbose_name='公式URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='toy_app.Tag', verbose_name='タグ'),
        ),
    ]
