# Generated by Django 2.1 on 2018-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0009_auto_20180925_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amazon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Amazonアフィリエイト'),
        ),
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ASIN'),
        ),
    ]
