# Generated by Django 2.1 on 2018-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0011_auto_20180927_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='タグ説明'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='toy_app.Tag', verbose_name='タグ'),
        ),
    ]
