# Generated by Django 2.1 on 2018-11-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0012_auto_20180930_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
    ]
