# Generated by Django 2.1 on 2018-10-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0003_auto_20181002_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
