# Generated by Django 2.1 on 2018-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0004_auto_20181008_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='画像数'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='字数'),
        ),
    ]
