# Generated by Django 2.1 on 2018-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0005_auto_20181008_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正規表現'),
        ),
    ]
