# Generated by Django 2.1 on 2018-10-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0006_heritage_regex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='another_name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='article',
            name='word_count_per_image',
            field=models.IntegerField(blank=True, default=0, verbose_name='画像あたり字数'),
        ),
    ]
