# Generated by Django 2.1 on 2018-10-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0007_auto_20181019_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(max_length=255, verbose_name='略称'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='formal_name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
    ]
