# Generated by Django 2.1 on 2018-10-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0009_auto_20181019_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='非表示'),
        ),
    ]
