# Generated by Django 2.1 on 2018-10-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0010_article_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='サイト説明文')),
            ],
        ),
    ]
