# Generated by Django 2.1 on 2018-10-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0012_country_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='正式名称'),
        ),
    ]
