# Generated by Django 2.1 on 2018-10-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0013_auto_20181021_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_name',
            new_name='formal_name',
        ),
    ]
