# Generated by Django 2.1 on 2018-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0016_auto_20181023_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaster',
            name='contact_form_utl',
            field=models.URLField(blank=True, null=True, verbose_name='お問い合わせフォームURL'),
        ),
    ]
