# Generated by Django 2.1 on 2018-10-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0017_auto_20181024_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaster',
            name='dummy',
            field=models.TextField(blank=True, null=True, verbose_name='dummy'),
        ),
    ]
