# Generated by Django 2.1 on 2018-10-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0018_sitemaster_dummy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',)},
        ),
    ]
