# Generated by Django 2.1 on 2018-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0020_auto_20181103_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='formal_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='正式名称'),
        ),
    ]
