# Generated by Django 2.1 on 2018-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0021_auto_20181103_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_count_per_image',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='画像あたり字数'),
        ),
    ]
