# Generated by Django 2.1 on 2018-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0022_auto_20181103_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通称'),
        ),
    ]
