# Generated by Django 2.1 on 2018-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0023_country_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明文'),
        ),
    ]
