# Generated by Django 2.1 on 2018-11-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0024_heritage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('short_name',)},
        ),
    ]
